/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DetectionsIndexRouteImport } from './routes/detections.index'
import { Route as DetectionsIdRouteImport } from './routes/detections.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsIndexRoute = DetectionsIndexRouteImport.update({
  id: '/detections/',
  path: '/detections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsIdRoute = DetectionsIdRouteImport.update({
  id: '/detections/$id',
  path: '/detections/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/detections/$id': typeof DetectionsIdRoute
  '/detections/': typeof DetectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/detections/$id': typeof DetectionsIdRoute
  '/detections': typeof DetectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/explainability': typeof ExplainabilityRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/detections/$id': typeof DetectionsIdRoute
  '/detections/': typeof DetectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/analytics'
    | '/explainability'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/detections/$id'
    | '/detections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/analytics'
    | '/explainability'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/detections/$id'
    | '/detections'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/analytics'
    | '/explainability'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/detections/$id'
    | '/detections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  MonitoringRoute: typeof MonitoringRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  DetectionsIdRoute: typeof DetectionsIdRoute
  DetectionsIndexRoute: typeof DetectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/': {
      id: '/detections/'
      path: '/detections'
      fullPath: '/detections/'
      preLoaderRoute: typeof DetectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections/$id': {
      id: '/detections/$id'
      path: '/detections/$id'
      fullPath: '/detections/$id'
      preLoaderRoute: typeof DetectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  MonitoringRoute: MonitoringRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  DetectionsIdRoute: DetectionsIdRoute,
  DetectionsIndexRoute: DetectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
